/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danitabuyo.colecedillo.CONTROLLER;

import com.danitabuyo.colecedillo.DAO.Conexion;
import com.danitabuyo.colecedillo.MODEL.Alumnos;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import com.danitabuyo.colecedillo.MODEL.Clases;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cedillo15
 */
public class ColeCedillo extends javax.swing.JFrame {

    DefaultTableModel modelo;

    /**
     * Creates new form ColeCedillo
     */
    public ColeCedillo() {
        initComponents();

        //Vamos a preparar los títulos de la tabla con un array y cargar el modelo
        String[] titulos_tabla = {"ID", "Nombre", "Apellidos", "Clase", "Notas"};
        modelo = new DefaultTableModel(null, titulos_tabla);
        tbtablaalumnos.setModel(modelo);

        //Lanzamos el método mostrarDatos al inicio para que cargue la tabla
        this.mostarDatos();
        this.limpiarCajas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btagregar = new javax.swing.JButton();
        btmodificar = new javax.swing.JButton();
        btborrar = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtablaalumnos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        txtnotas = new javax.swing.JTextField();
        txtaula = new javax.swing.JTextField();
        txtnombrealum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar-el-archivo.png"))); // NOI18N
        btagregar.setText("Insertar");
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });

        btmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boton-editar.png"))); // NOI18N
        btmodificar.setText("Modificar");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });

        btborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/borrar-archivo.png"))); // NOI18N
        btborrar.setText("Borrar");
        btborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btborrarActionPerformed(evt);
            }
        });

        btsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salida.png"))); // NOI18N
        btsalir.setText("Salir");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Alumno");

        tbtablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbtablaalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtablaalumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtablaalumnos);

        jLabel3.setText("Apellidos Alumno");

        jLabel4.setText("Aula");

        jLabel5.setText("Notas");

        txtapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidosActionPerformed(evt);
            }
        });

        txtnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotasActionPerformed(evt);
            }
        });

        txtaula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaulaActionPerformed(evt);
            }
        });

        txtnombrealum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrealumActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS ALUMNOS");

        jLabel6.setText("Id");

        txtid.setEditable(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/boton-cancelar.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagregar))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombrealum, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addComponent(txtapellidos)
                                .addComponent(txtaula)
                                .addComponent(txtnotas)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnombrealum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btagregar)
                    .addComponent(btmodificar)
                    .addComponent(btborrar)
                    .addComponent(btcancelar))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btsalir))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
//conectamos con la BBDD
        Conexion conexion = new Conexion();
        Alumnos alumno = recuperarDatosInterfaz();
        String insertar_alumno = String.format("insert into alumnos (id, nombre, apellidos, aula, notas) "
                + "values (null, '%s', '%s', '%s', '%s')",
                alumno.getNombre(), alumno.getApellidos(), alumno.getAula(), alumno.getNota());
        
        conexion.ejecutarSQL(insertar_alumno);
        this.mostarDatos();
        this.limpiarCajas();


    }//GEN-LAST:event_btagregarActionPerformed

    private void txtapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosActionPerformed

    private void txtnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotasActionPerformed

    private void txtaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaulaActionPerformed

    private void btborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrarActionPerformed
//conectamos con la BBDD
        Conexion conexion = new Conexion();
        Alumnos alumno = recuperarDatosInterfaz();
        //Se pone %d pq hace referencia al número entero del id
        String borrar_alumno = String.format("DELETE FROM alumnos WHERE id = %d", alumno.getId());
        conexion.ejecutarSQL(borrar_alumno);
        this.mostarDatos();


    }//GEN-LAST:event_btborrarActionPerformed

    private void txtnombrealumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrealumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrealumActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        Conexion conexion = new Conexion();
        Alumnos alumno = recuperarDatosInterfaz();
        String modificar_alumno = String.format("update  alumnos set nombre='%s', apellidos='%S', aula='%s', notas='%s' where id = %d", alumno.getNombre(), alumno.getApellidos(), alumno.getAula(), alumno.getNota(), alumno.getId());

        conexion.ejecutarSQL(modificar_alumno);
        this.mostarDatos();
        this.limpiarCajas();
    }//GEN-LAST:event_btmodificarActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btsalirActionPerformed

    private void tbtablaalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtablaalumnosMouseClicked

//Comprobando si se dio click al botón
        if (evt.getClickCount() == 1) {
            //Casteamos la info que viene del evt

            JTable receptor = (JTable) evt.getSource();
            txtid.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(), 0));
            txtnombrealum.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(), 1));
            txtapellidos.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(), 2));
            txtaula.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(), 3));
            txtnotas.setText((String) receptor.getModel().getValueAt(receptor.getSelectedRow(), 4));

        }
        btmodificar.setEnabled(true);
        btagregar.setEnabled(false);
        btborrar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_tbtablaalumnosMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
            this.limpiarCajas();

        // TODO add your handling code here:
    }//GEN-LAST:event_btcancelarActionPerformed

    public Alumnos recuperarDatosInterfaz() {
        Alumnos alumnos = new Alumnos();
        int id = (txtid.getText().isEmpty()) ? 0 : Integer.parseInt(txtid.getText());
        String notasalum = txtnotas.getText();
        double notas = Double.parseDouble(notasalum);
        alumnos.setNombre(txtnombrealum.getText());
        alumnos.setApellidos(txtapellidos.getText());
        alumnos.setAula(txtaula.getText());
        alumnos.setNota(notas);

        return alumnos;
    }

    public Alumnos insertarAlumnos() {
        Alumnos alumnos = new Alumnos();
        String nombrealum = txtnombrealum.getText();
        String apellidosalum = txtapellidos.getText();
        String aulaalum = txtaula.getText();
        String notasalum = txtnotas.getText();
        double notas = Double.parseDouble(notasalum);
        // int id;
        // id = Integer.parseInt(txtid.getText());
        // alumnos.setId(id);
        alumnos.setNombre(nombrealum);
        alumnos.setApellidos(apellidosalum);
        alumnos.setAula(aulaalum);
        alumnos.setNota(notas);

        return alumnos;

    }

    private void mostarDatos() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        Conexion conexion = new Conexion();
        //Mostramos datos por consola
        try {
            ResultSet registros = conexion.consultarDatos("select * from alumnos ");
            while (registros.next()) {
                System.out.println(registros.getString("id"));
                System.out.println(registros.getString("nombre"));
                System.out.println(registros.getString("apellidos"));
                System.out.println(registros.getString("aula"));
                System.out.println(registros.getString("notas"));

                //Creo el objeto alumno con los datos recuperados
                Object[] alumno = {registros.getString("id"), registros.getString("nombre"),
                    registros.getString("apellidos"), registros.getString("aula"), registros.getString("notas")};

                //Agregamos al modelo el objeto alumno
                modelo.addRow(alumno);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void limpiarCajas() {
        txtid.setText("");
        txtnombrealum.setText("");
        txtapellidos.setText("");
        txtaula.setText("");
        txtnotas.setText("");
        btmodificar.setEnabled(false);
        btagregar.setEnabled(true);
        btborrar.setEnabled(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColeCedillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColeCedillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColeCedillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColeCedillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColeCedillo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagregar;
    private javax.swing.JButton btborrar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btmodificar;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtablaalumnos;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtaula;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombrealum;
    private javax.swing.JTextField txtnotas;
    // End of variables declaration//GEN-END:variables
}
